# Generated by Django 3.2.11 on 2024-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_speed', models.FloatField()),
                ('vehicle_direction', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Forward', 'Forward'), ('Backward', 'Backward')], default='Forward', max_length=50, verbose_name='Direction')),
                ('events', models.CharField(choices=[('Regular', 'Regular'), ('Impact', 'Impact'), ('Speed bump', 'Speed bump'), ('Spinout', 'Spinout')], default='Regular', max_length=50, verbose_name='Event')),
                ('vehicle_acceleration', models.FloatField()),
            ],
        ),
    ]
