# Generated by Django 3.2.11 on 2024-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='events',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Impact', 'Impact'), ('Speed bump', 'Speed bump'), ('Spinout', 'Spinout'), ('Pot hole', 'Pot hole')], default='Regular', max_length=50, verbose_name='Event'),
        ),
    ]
